version: '3.5'

services:
  api:
    build: ./app
    ports:
      - '8080:8080'
  database:
    image: 'postgres'
    environment:
      POSTGRES_DB: 'e_menu'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: '123456'
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  data:
